.travis.yml
:information_desk_person: Ruby 2.1.0 was released on 25 December 2013 ([release announcement](https://www.ruby-lang.org/en/news/2013/12/25/ruby-2-1-0-is-released/)). This change adds support for this version of MRI Ruby to the Travis CI build plan.
=> Adds support for MRI Ruby v2.1

lib/bigcommerce/api.rb
I added method for orders_count including filter support, as per
https://developer.bigcommerce.com/api/stores/v2/orders#get-a-count-of-orders
and fix products_count to also allow filters
=> Adding orders_count method, and fix up products_count

bigcommerce.gemspec
Fixes Issue #91. 
Slightly reworded and removed the ```\``` characters from the description. See the issue for more details.
=> Update Gemspec description. Fixes #91.

bigcommerce.gemspec
:information_desk_person: The `platform` attribute is required by the [RubyGems gemspec specification][gemspec-spec]. This change sets it to the local operating system and architecture.
[gemspec-spec]: http://guides.rubygems.org/specification-reference/#platform=
=> Add required platform attribute to gemspec

Gemfile, bigcommerce.gemspec
:information_desk_person: These changes explicitly move the development dependencies from the Gemfile to the gemspec for visibility and to aid keeping the code and dependency manifest in sync.
Fixes #93
=> Move development dependencies to gemspec

CHANGELOG.md, Guardfile, lib/bigcommerce/exception.rb, spec/bigcommerce/unit/exception_spec.rb
Fix: We should rescue the JSON parsing
cc @mattolson @pedelman
=> fix #100 bug when response is a string

bigcommerce.gemspec, examples/marketing/banner.rb, examples/marketing/gift_certificates.rb, lib/bigcommerce/resources/marketing/banner.rb, lib/bigcommerce/resources/marketing/gift_certificates.rb
Update the ruby gem to add gift certificates and banners as resources.
=> Add gift certs and banners as resources

examples/exception_handling.rb
Before this PR:
```
$ ruby examples/exception_handling.rb
examples/exception_handling.rb:45:in `<main>': uninitialized constant Bigcommerce::HttpError::ERRORS (NameError)
```
After this PR:
```
$ ruby examples/exception_handling.rb
#<Bigcommerce::BadRequest: Bigcommerce::BadRequest>
#<Bigcommerce::Unauthorized: Bigcommerce::Unauthorized>
#<Bigcommerce::Forbidden: Bigcommerce::Forbidden>
#<Bigcommerce::NotFound: Bigcommerce::NotFound>
#<Bigcommerce::MethodNotAllowed: Bigcommerce::MethodNotAllowed>
#<Bigcommerce::NotAccepted: Bigcommerce::NotAccepted>
#<Bigcommerce::TimeOut: Bigcommerce::TimeOut>
#<Bigcommerce::ResourceConflict: Bigcommerce::ResourceConflict>
#<Bigcommerce::TooManyRequests: Bigcommerce::TooManyRequests>
#<Bigcommerce::InternalServerError: Bigcommerce::InternalServerError> …
```
=> Fix exception handling example typo

lib/bigcommerce/resources/products/sku.rb
Got a list of attributes from: https://developer.bigcommerce.com/api/objects/v2/sku
Fixes #110 
Ex response:
```rb
Bigcommerce::Sku.all(4)
=> [#<Bigcommerce::Sku adjusted_price="12345.0000" adjusted_weight="123.0000" bin_picking_number="1234567" cost_price="123.0000" id=18 image_file="" inventory_level=0 inventory_warning_level=0 is_purchasing_disabled=false options=[{:product_option_id=>1, :option_value_id=>73}] price="12345.0000" product_id=4 purchasing_disabled_message="" sku="fdjhjk" upc="djksbgkjsdb" weight="123.0000">]
```
=> Update the SKU resource based on developer documentation

lib/bigcommerce/resources/content/blog_post.rb
The removed attributes are unused in the current api and can safely be removed.
See: https://developer.bigcommerce.com/api/stores/v2/blog/posts
=> Update BlogPost resource to have correct attributes

lib/bigcommerce/resources/content/blog_tag.rb
The `id` field is not used.
Based on information from: https://developer.bigcommerce.com/api/stores/v2/blog/tags
Ex.
```
$ ruby examples/content/blog_tag.rb
#<Bigcommerce::BlogTag post_ids=[1] tag="Blog">
#<Bigcommerce::BlogTag post_ids=[1] tag="Seo">
```
=> Update BlogTag resource

examples/marketing/gift_certificates.rb
There was a typo which caused this example to not work.
```
$ ruby examples/marketing/gift_certificates.rb
#<Bigcommerce::GiftCertificates amount="100.0000" balance="100.0000" code="98679a2eef4573465f12" customer_id="0" expiry_date="0" from_email="othertest@test.com" from_name="Test2" id=7 message="" order_id="0" purchase_date="1466472031" status="0" template=false to_email="test@test.com" to_name="Test">
#<Bigcommerce::GiftCertificates amount="100.0000" balance="100.0000" code="98679a2eef4573465f12" customer_id="0" expiry_date="0" from_email="othertest@test.com" from_name="Test2" id=7 message="" order_id="0" purchase_date="1466472031" status="0" template=false to_email="test@test.com" to_name="Test">
#<Bigcommerce::GiftCertificates amount="100.0000" balance="100.0000" …
```
=> Update the GiftCertificate example

examples/products/brand.rb, examples/products/configurable_field.rb, examples/products/option_set_option.rb, examples/products/product_option.rb, examples/products/product_review.rb, examples/products/product_rule.rb, examples/products/sku.rb, lib/bigcommerce/resources/products/google_product_search_mapping.rb, lib/bigcommerce/resources/products/option_value.rb, lib/bigcommerce/resources/products/product.rb, lib/bigcommerce/resources/products/product_review.rb, spec/bigcommerce/unit/resources/products/product_review_spec.rb
I may remove the ProductReview resource diff depending how quickly I hear back on #107
=> Update examples for product and update resources

.gitignore, CHANGELOG.md, CONTRIBUTING.md, DEPENDENCIES.md, README.md, bigcommerce.gemspec, examples/customers/customer_login.rb, lib/bigcommerce.rb, lib/bigcommerce/resources/customers/customer.rb, spec/bigcommerce/unit/resources/customers/customer_spec.rb
* Add instance method on Customer object to generate
a login token for that customer. This only works if
the app has the store_v2_customer_login scope and is
installed on the store.
=> Add support for customer login

lib/bigcommerce/connection.rb
#136 adds the `accept-encoding: gzip` header to requests, but does not handle gzip-encoded respnoses. This adds `FaradayMiddleware::Gzip` to the middleware stack to handle requested gzip-encoded bodies.
=> Handle gzipped response bodies with FaradayMiddleware::Gzip

CHANGELOG.md, Rakefile, bigcommerce.gemspec, lib/bigcommerce/connection.rb, lib/bigcommerce/resources/geography/country.rb, lib/bigcommerce/resources/geography/state.rb, lib/bigcommerce/resources/orders/order_coupon.rb, lib/bigcommerce/resources/orders/order_message.rb, lib/bigcommerce/resources/orders/order_product.rb, lib/bigcommerce/resources/orders/order_shipping_address.rb, lib/bigcommerce/resources/orders/order_status.rb, lib/bigcommerce/resources/orders/order_tax.rb, lib/bigcommerce/resources/products/configurable_field.rb, lib/bigcommerce/resources/products/product_option.rb, lib/bigcommerce/resources/shipping/shipping_method.rb, lib/bigcommerce/resources/tax/tax_class.rb
- Update gemspec to fix Faraday gem version to point to latest patch
version
- Update rubocop issues
- Support setting ssl options for OAuth API mode
=> Fix issue which caused Faraday to resolve to latest version.

lib/bigcommerce/resources/customers/customer.rb
`Bigcommerce::Customer#login_token` does not create valid JWTs. 
- Add missing `typ` header
- Add missing `redirect_to` payload option
=> Fix Bigcommerce::Customer#login_token JWT

bigcommerce.gemspec
* The current version requirements of this gem for JWT and Hashie gems are highly outdated and cause major compatibility issues with basically any other modern gems (like omniauth or Google api gems).
* Update JWT and Hashie gems to be able to get newer versions since 
Specs appear to be passing, and update was battle-tested at @feracommerce 
* I checked the [change logs for Hashie gem here](https://github.com/hashie/hashie/releases) to ensure that there are no breaking changes
* I checked the [change logs for JWT gem here](https://github.com/jwt/ruby-jwt/releases) to ensure that there are no breaking changes
JWT update seems to have added a ton of fixes as well that should be allowed.
=> Update JWT and Hashie gem requirements

.rubocop.yml, CHANGELOG.md, lib/bigcommerce/exception.rb, spec/bigcommerce/unit/exception_spec.rb
Updates how response headers are handled to accommodate lowercased header names. New unit test included to verify functionality. Plus an edit in `.rubocop.yml` to get rid of a rubocop error.
=> APPEX-243: adds case-insensitive handling for HTTP header titles

CHANGELOG.md, README.md
Update CCI/CodeClimate/etc badges, changelog. gemnasium is not a thing anymore, so removing.
=> Update badges, changelog

CHANGELOG.md, RELEASING.md, bigcommerce.gemspec, lib/bigcommerce/config.rb, lib/bigcommerce/resources/orders/order.rb, lib/bigcommerce/version.rb
Updating the Faraday gem from 0.17.x to 1.1.x.
Misc:
* correcting entries in the CHANGELOG.md
The Faraday changelogs can be reviewed here:
- [0.17.4](https://github.com/lostisland/faraday/blob/main/CHANGELOG.md#v0174)
- [1.1.0](https://github.com/lostisland/faraday/blob/main/CHANGELOG.md#v110-2020-10-17)
* RSpec tests pass
* Tested creating a client and manipulating resources successfully
*
=> Loosen Faraday dependency to ~> 1.1.0

CHANGELOG.md, lib/bigcommerce/version.rb
Preparations for 1.1.0 release, which supports Ruby 3.2.
=> Preparing for release, 1.1.0

lib/bigcommerce/resources/customers/customer.rb
Form fields exist on Customer but are missing from the customer resource object.
Schema definition:
```
$ curl https://developer.bigcommerce.com/api-reference/store-management/customers-v2/BigCommerce_Customers_API.oas2.json \
| jq '.definitions.Customer.properties.form_fields'
```
```javascript
{
"description": "Array of custom fields. This is a READ-ONLY field; do not set or modify its value in a POST or PUT request.",
"type": "array",
"items": {
"title": "Form Fields",
"type": "object",
"properties": {
"name": {
"description": "Name of the form field",
"type": "string",
"example": "License Id"
},
"value": {
"description": "Value of the form field",
"type": "string",
"example": "123BAF"
}
}
}
}
```
=> add form_fields to Customer
